assignment_scheduler/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='main_menu'),
    url(r'^assignment_list/$', views.assignment_list, name='assignment_list'),
    url(r'^assignment/new/$', views.add_assignment, name='add_assignment'),
    # url(r'^$', views.view_all_assignments, name='view_all_assignments'),
    # url(r'^delete_assignment/$', views.delete_assignment, name='delete_assignment'),
    url(r'^assignment/(?P<id>\d+)/$', views.assignment_read, name='assignment_read'),
    url(r'^delete_assignment/(?P<id>\d+)/$', views.assignment_delete, name='assignment_delete'),
    url(r'^check_due_assignments/$', views.check_due_assignments, name='check_due_assignments'),
    url(r'^assignment/complete/(?P<id>\d+)/$', views.assignment_complete, name='assignment_complete'),

]

homework_scheduler/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('assignment_scheduler.urls')),
]

assignment_scheduler/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class ScheduleItem(models.Model):

    class_name = models.CharField(max_length=200)
    name = models.CharField(max_length=100)
    complete = models.BooleanField()
    description = models.TextField()
    due_date = models.DateTimeField(blank=True, null=True)


    def __repr__(self):
        return "ID: {}; Name: {}; IsComplete: {}; Description: {}; DueDate: {}".format(self.id, self.name, self.complete, self.description, self.due_date)

assignment_scheduler/forms.py
from django import forms
from .models import ScheduleItem

class AddAssignmentForm(forms.ModelForm):
    class Meta:
        model = ScheduleItem
        # todo Figure out how to get a date time picker for due_date
        fields = ('class_name', 'name', 'complete', 'description', 'due_date')

assignment_scheduler/views.py
from django.shortcuts import render, redirect
from .models import ScheduleItem
from .forms import AddAssignmentForm
from django.utils import timezone

def index(request):
    assignments_list = ScheduleItem.objects.all()
    assignments_due_today = assignments_list.filter(due_date=timezone.now().date())
    assignments_due_tomorrow = assignments_list.filter(due_date=(timezone.now() + timezone.timedelta(days=1)).date())
    assignments_past_due = assignments_list.filter(due_date__lt=timezone.now().date())
    print(len(assignments_past_due))
    return render(request, 'assignment_scheduler/index.html', {'due_today':assignments_due_today,'due_tomorrow':assignments_due_tomorrow,'past_due':assignments_past_due})

def assignment_list(request):
    assignments = ScheduleItem.objects.all()
    return render(request, 'assignment_scheduler/assignment_list.html', {'assignments': assignments})

def add_assignment(request):
    if request.method =="POST":
        form = AddAssignmentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            assignment = ScheduleItem.objects.get(id=post.pk)
            return render(request, 'assignment_scheduler/read_one_assignment.html', {'assignment': assignment})
    else:
        form = AddAssignmentForm()
    return render(request, 'assignment_scheduler/add_assignment.html', {'form': form})

def assignment_read(request, id):
    assignment = ScheduleItem.objects.get(id=id)
    return render(request, 'assignment_scheduler/read_one_assignment.html', {'assignment':assignment})

def assignment_delete(request, id):
    ScheduleItem.objects.get(id=id).delete()
    assignments = ScheduleItem.objects.all()
    return redirect('/assignment_list/', {'assignments':assignments})

def check_due_assignments(request):
    return render(request, 'assignment_scheduler/check_due_assignments.html', {})

def assignment_complete(request, id):
    assignment = ScheduleItem.objects.get(id=id)
    assignment.complete = True
    assignment.save()

    assignments = ScheduleItem.objects.all()
    return redirect('/assignment_list/', {'assignments':assignments})

assignment_scheduler/templates/assignment_scheduler/add_assignment.html
{% extends "assignment_scheduler/base.html" %}

{% block content %}
  <script>
    $(function(){
      $('#id_due_date').datepicker()
    })
  </script>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>New Assignment</h1>
    </div>
    <div class="panel-body">
        <form method="POST" class="post-form">{% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="save btn-default">Save</button>
        </form>

    </div>
  </div>

{% endblock %}

assignment_scheduler/templates/assignment_scheduler/assignment_list.html
{% extends "assignment_scheduler/base.html" %}

  {% block content %}
    {% for assignment in assignments %}

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3><a href="/assignment/{{ assignment.id }}/">Assignment: {{ assignment.name }}</a></h3>
      </div>

      <div class="panel-body">
        <h5>Class:</h5>
        {{ assignment.class_name }}
        <h5>Description:</h5>
        <p>{{ assignment.description|linebreaksbr }}</p>
        {% if assignment.complete %}
          <p class="alert alert-success">This assignment is complete</p>
        {% else %}
          <p class="alert alert-warning">This assignment is not complete</p>
        {% endif %}
      </div>

      <div class="panel-footer">
        <p>Due Date: {{ assignment.due_date }}</p>
        <button type="button" class="btn-group">
          <a href="/assignment/complete/{{ assignment.id }}/">Complete</a>
        </button>
        <div class="btn-group">
          <button type="button">
            Delete
          </button>
        </div>

      </div>

    </div>

    {% endfor %}

  {% endblock %}

assignment_scheduler/templates/assignment_scheduler/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <title>Homework Scheduler</title>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- The viewport is the visible area of a page. Pages may be wider
    than the screen or browser window; and pages are often longer than
    the browser window. This tag sets the width of the page equal to the
    width of the browser window. The height stays the same. -->
    <meta name="viewport" content="width=device-width initial-scale=1">


    <!-- Include Bootstrap. This downloads Bootstrap from a CDN. You can
     also host Bootstrap on your server, but it's usually faster for the
     user for their browser to fetch it from a CDN. -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Nav components, and dropdowns, need Bootstrap's JavaScript to do anything.
    And JavaScript requires JQuery, so include that too -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

  </head>

  <body>
    <div class="main">

      <div class="page>">

        <div class="header">

          <div class="container">
            <!-- Top Banner with text -->
            <div class="jumbotron">
              <h1>Class Homework Scheduler</h1>
              <p>Manage your homework assignments easily!</p>
            </div>

            <!-- Top menu bar -->
            <div class="topmenu">
              <!-- List of top menu list items -->
              <ul class="nav nav-tabs">
                <li><a href="/">Main Menu</a></li> <!-- Main menu -->
                <li><a href="/assignment/new/">Add Assignment</a></li> <!-- Add assignment -->
                <li><a href="/assignment_list">View all Assignments</a></li> <!--List all Assignments -->
                <!-- <li><a href="/check_due_assignments">Check for due Assignments</a></li> <!-- Check for assignments due -->
              </ul>
            </div>

          <!-- Main ontent div -->
          <div class="content">

            {% block content %}   <!-- A block that the child template will fill in -->

            {% endblock %}
          </div>
        </div>

        <!-- Footer div -->
        <div class="footer">

        </div>

      </div>

    </div>

  </body>
</html>

assignment_scheduler/templates/assignment_scheduler/check_due_assignments.html
{% extends "assignment_scheduler/base.html" %}

{% block content %}

    <div>
      <p>Work in Progress</p>
    </div>

{% endblock %}

assignment_scheduler/templates/assignment_scheduler/delete_assignment.html
  {% extends "assignment_scheduler/base.html" %}

  {% block content %}

    <!-- Don't need -->

  {% endblock %}

assignment_scheduler/templates/assignment_scheduler/error.html
  {% extends "base.html" %}

  {% block content %}
    <div>
      <h3>An error has occurred</h3>
    </div>
  {% endblock %}

assignment_scheduler/templates/assignment_scheduler/index.html
{% extends "assignment_scheduler/base.html" %}

{% block content %}

  <div>
    <h2>Your Past Due Assignments:</h2>
    {% if past_due|length > 0 %}
      {% for assignment in past_due %}
        {% if not assignment.complete %}
          <p class="alert alert-danger">Class: {{ assignment.class_name }} Assignment: <a href="/assignment/{{ assignment.id }}/">{{ assignment.name }}</a></p>
        {% endif %}
      {% endfor %}
    {% else %}
      <p class="alert alert-success">No Overdue Assignments</p>
    {% endif %}
  </div>

  <div>
    <h2>Your Upcoming Assignments:</h2>
    <h4>Due Today:</h4>
    {% if due_today|length > 0 %}
      {% for assignment in due_today %}
        {% if not assignment.complete %}
          <p class="alert alert-warning">Class: {{ assignment.class_name }} Assignment: <a href="/assignment/{{ assignment.id }}/">{{ assignment.name }}</a></p>
          {% else %}
          <p class="alert alert-success">Class: {{ assignment.class_name }} Assignment: <a href="/assignment/{{ assignment.id }}/">{{ assignment.name }}</a></p>
        {% endif %}
      {% endfor %}
    {% endif %}
    <h4>Due Tomorrow:</h4>
    {% if due_tomorrow|length > 0 %}
      {% for assignment in due_tomorrow %}
        {% if not assignment.complete %}
          <p class="alert alert-warning">Class: {{ assignment.class_name }} Assignemnt: <a href="/assignment/{{ assignment.id }}/">{{ assignment.name }}</a></p>
        {% else %}
          <p class="alert alert-success">Class: {{ assignment.class_name }} Assignemnt: <a href="/assignment/{{ assignment.id }}/">{{ assignment.name }}</a></p>
        {% endif %}
      {% endfor %}
    {% else %}
      <p>None</p>
    {% endif %}
  </div>



{% endblock %}

assignment_scheduler/templates/assignment_scheduler/read_one_assignment.html
{% extends "assignment_scheduler/base.html" %}

  {% block content %}

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><a href>{{ assignment.name }}</a></h3>
        </div>

        <div class="panel-body">
          <p>{{ assignment.description|linebreaksbr }}</p>
          {% if assignment.complete %}
            <p class="alert alert-success">This assignment is complete</p>
          {% else %}
            <p class="alert alert-warning">This assignment is not complete</p>
          {% endif %}
        </div>

        <div class="panel-footer">
          <p>Due Date: {{ assignment.due_date }}</p>
        </div>

      </div>

  {% endblock %}

assignment_scheduler/templates/assignment_scheduler/view_all_assignments.html
  {% extends "base.html" %}

  {% block content %}

          {% for item in assignment_list %}

            <form action="/update_item" method="post">
              ID: {{ item.id }}
              <input type='hidden' name='item_id' value={{ item.id }}>
              Class Name: <input type="text" name="class_name" value="{{ item.class_name }}">
              Name: <input type="text" name="name" value="{{ item.name }}">
              Complete (True/False): <input type="text" name="complete" value="{{ item.complete }}">
              Description: <input type="text" name="description" value="{{ item.description }}">
              Date Due: <input type="date" name="due_date" value="{{ item.date_due }}">
              <input type="submit" name="button" value="Update">
            </form>

          {% endfor %}

  {% endblock %}